<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <AssemblyName>FlowMeta</AssemblyName>
    <Product>FlowMeta</Product>
    <FileDescription>FlowMeta</FileDescription>
    <Version>1.0.3</Version>
    <AssemblyVersion>1.0.3.0</AssemblyVersion>
    <FileVersion>1.0.3.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="FlowMetaLicenseAdmin\**\*.cs" />
    <EmbeddedResource Remove="FlowMetaLicenseAdmin\**\*" />
    <None Remove="FlowMetaLicenseAdmin\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.8" />
  </ItemGroup>

</Project>
